#!/bin/sh

[ "$#" -eq 0 ] && exit 1
if [ -n $(command -v curl) ]; then
  url=$(curl -sIL -o /dev/null -w '%{url_effective}' "$1")
else  
  url="$1"
fi
url=$(echo "${url}" | perl -p -e 's/(\?|\&)?utm_[a-z]+=[^\&]+//g;' -e 's/(#|\&)?utm_[a-z]+=[^\&]+//g;')
author="$3"
title="$2"

grep -q "${url}\t${title}\t${author}" ~/.local/share/nitter/marks || echo "${author}\t${url}\n${title}" >> ~/.local/share/nitter/marks
