# Shell variables
# Generated by &#39;wal&#39;
wallpaper=&#39;/tmp/tmp4hajcv_7&#39;

# Special
background=&#39;#010410&#39;
foreground=&#39;#cbcfdc&#39;
cursor=&#39;#cbcfdc&#39;

# Colors
color0=&#39;#010410&#39;
color1=&#39;#607A9A&#39;
color2=&#39;#6482A3&#39;
color3=&#39;#738DAF&#39;
color4=&#39;#7D9BC2&#39;
color5=&#39;#8A9CB9&#39;
color6=&#39;#97A7C6&#39;
color7=&#39;#cbcfdc&#39;
color8=&#39;#8e909a&#39;
color9=&#39;#607A9A&#39;
color10=&#39;#6482A3&#39;
color11=&#39;#738DAF&#39;
color12=&#39;#7D9BC2&#39;
color13=&#39;#8A9CB9&#39;
color14=&#39;#97A7C6&#39;
color15=&#39;#cbcfdc&#39;

# FZF colors
export FZF_DEFAULT_OPTS=&quot;
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
&quot;

# Fix LS_COLORS being unreadable.
export LS_COLORS=&quot;$LS_COLORS:su=30;41:ow=30;42:st=30;44:&quot;
