#!/bin/sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.
# If no url given. Opens browser. For using script as $BROWSER.

web="$BROWSER"
edit="$TERMINAL -e $EDITOR"
podcast="$TERMINAL -e mpv --no-audio-display"
video="mpv --really-quiet"
picture="mpv --aid=no"
document="$READER"

input="$1"

if [ -z "$input" ]; then
    exit 1
else
    notify-send "linkhandler -> trying to open" "$input"
fi

open() {
    eval "$2" "$1 $input >/dev/null 2>&1" &
}

open_tmp() {
    curl -sL "$input" >"/tmp/$(printf "%s" "$input" \
        | sed "s/.*\///")" \
        && eval "$1 /tmp/$(printf "%s" "$input" \
        | sed "s/.*\///") >/dev/null 2>&1" &
}

case "$input" in
    *mkv \
        | *mp4 \
        | *webm \
        | *'youtube.com/watch'* \
        | *'youtube.com/playlist'* \
        | *'youtu.be'*)
            open "$video" "tsp"
    ;;
    *mp3 \
        | *ogg \
        | *flac \
        | *opus)
            open "$podcast" "tsp"
    ;;
    *jpg \
        | *jpe \
        | *jpeg \
        | *png \
        | *gif \
        | *webp)
            open_tmp "$picture"
    ;;
    *pdf \
        | *ps \
        | *djvu \
        | *epub \
        | *cbr \
        | *cbz)
            open_tmp "$document"
    ;;
    *torrent \
        | 'magnet\:'* \
        | *metalink \
        | *iso \
            open "$download"
    ;;
    *)
        if [ -f "$input" ]; then
            open "$edit"
        else
            open "$web"
        fi
    ;;
esac



    case "$1" in
	*mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*)
		mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && feh "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source*)
		ts curl -LO "$1" >/dev/null 2>&1 & ;;
	*)
		if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
		else $BROWSER "$1" >/dev/null 2>&1 & fi ;;
esac
