#!/data/data/com.termux/files/usr/bin/bash
HOME=/Users/bluetooth
. "${HOME}"/.zprofile &>/dev/null

podcast="$TERMINAL -e mpv --no-audio-display"
video="mpv --really-quiet --player-operation-mode=pseudo-gui"
picture="mpv --aid=no"
document="$READER"
download="aria2c"

input="$1"

if [ -z "$input" ]; then
    exit 1
else
    notify-send "linkhandler -> trying to open" "$input"
fi

open() {
    eval "$2" "$1 $input >/dev/null 2>&1" &
}

open_tmp() {
    curl -sL "$input" >"/tmp/$(printf "%s" "$input" \
        | sed "s/.*\///")" \
        && eval "$1 /tmp/$(printf "%s" "$input" \
        | sed "s/.*\///") >/dev/null 2>&1" &
}

case "$input" in
    *mkv \
        | *mp4 \
        | *webm \
        | *'youtube.com/watch'* \
        | *'yewtu.be'* \
        | *'youtube.com/playlist'* \
        | *'youtu.be'*)
            open "$video" "ts"
    ;;
    *mp3 \
        | *ogg \
        | *flac \
        | *opus)
            open "$podcast" "ts"
    ;;
    *jpg \
        | *jpe \
        | *jpeg \
        | *png \
        | *gif \
        | *webp)
            open_tmp "$picture"
    ;;
    *pdf \
        | *ps \
        | *djvu \
        | *epub \
        | *cbr \
        | *cbz)
            open_tmp "$document"
    ;;
    *torrent \
        | 'magnet\:'* \
        | *metalink \
        | *iso)
            open "$download"
    ;;
    *)
        if [ -f "$input" ]; then "$TERMINAL" -e "$EDITOR $1"
        else $BROWSER "$1" >/dev/null 2>&1 & fi ;;
esac
