#!/usr/bin/env bash

source ~/.secrets

curl -sS -X POST \
    -F "url=$1" \
    -F "tags=$2" \
    -F "consumer_key=$POCKET_CONSUMER_KEY" \
    -F "access_token=$POCKET_ACCESS_TOKEN" \
    https://getpocket.com/v3/add | jq 
