#!/usr/bin/env bash

set -ueo pipefail
d="$(date -I)"
downloads_dir="${HOME}/.cache/stars"
accept="${accept:-'application/vnd.github.v3+json'}"

help(){
    cat<<__EOF__
usage: starfetch <options> 

options:
     h, help
     ls, list
     dl, download
__EOF__
}

get() {
    url="$1"
    curl -sH -H "Accept: ${accept}" -H "Authorization: token ${GITHUB_TOKEN}" "${url}"
}

list() {
 user="$(git config user.username)"    
 get "https://api.github.com/users/${user}/starred?per_page=100" | jq '.'
}

download() {
    [ -z "${downloads_dir}" ] && mkdir -p "${downloads_dir}"
    list > "${downloads_dir}/s_$d.json"
}

case "$*" in
    help|h)
        help
        ;;
    list|ls)
        list
        ;;
    download|dl)
        shift
        download
        ;;
    *) help
        ;;

esac

