#!/bin/sh

eval "$(ssh-agent)" > /dev/null 2>&1

[ -f ~/.secrets ] && source ~/.secrets
[ -f ~/.config/sh/env ] && source ~/.config/sh/env
[ -f ~/.config/sh/functions ] && source ~/.config/sh/functions
[ -f ~/.config/sh/aliases ] && source ~/.config/sh/aliases

shopt -s extglob
shopt -s no_empty_cmd_completion
shopt -s checkwinsize
shopt -s histappend
set -o vi

# vim:ft=sh:
