#!/bin/sh

eval "$(ssh-agent)" > /dev/null 2>&1

[ -f "$HOME/.secrets" ] && . "$HOME/.secrets"
[ -f ~/.config/sh/env ] && . ~/.config/sh/env
[ -f ~/.config/sh/functions ] && . ~/.config/sh/functions
[ -f ~/.config/sh/aliases ] && . ~/.config/sh/aliases
[ -f "/usr/local/etc/profile.d/bash_completion.sh"  ] && . "/usr/local/etc/profile.d/bash_completion.sh"

shopt -s extglob
shopt -s no_empty_cmd_completion
shopt -s checkwinsize
shopt -s histappend
set -o vi

# vim:ft=sh:
