#!/bin/sh
alias -g \
	C="| wc -l" \
	D="DISPLAY=:0.0" \
	DN="/dev/null" \
	ED="export DISPLAY=:0.0" \
	EG="|& egrep" \
	EH="|& head" \
	EL="|& less" \
	ELS="|& less -S" \
	ETL="|& tail -20" \
	ET="|& tail" \
	F=" | fmt -" \
	G="| egrep" \
	H="| head" \
	HL="|& head -20" \
	Sk="*~(*.bz2|*.gz|*.tgz|*.zip|*.z)" \
	LL="2>&1 | less" \
	L="| less" \
	LS="| less -S" \
	M="| more" \
	NE="2> /dev/null" \
	NS="| sort -n" \
	NUL="> /dev/null 2>&1" \
	RNS="| sort -nr" \
	S="| sort" \
	TL="| tail -20" \
	T="| tail" \
	US="| sort -u" \
	VM="/var/log/messages" \
	X0G="| xargs -0 egrep" \
	X0="| xargs -0" \
	XG="| xargs egrep" \
	XS="fzf | xargs ls -l" \
	X="| xargs" \
	UL="| pup 'a attr{href}'" \
	FU="| urlscan" \
	JS="| gron | fzf" \
	CS="| awk '{print \$1}'" \
	CE="| awk '{print \$NF}'" \
	JL="| jc --ls | jq '.[].filename'" \
	EE="| xargs open -a MacVim"
